/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUpdatesRouteImport } from './routes/dashboard/updates'
import { Route as DashboardTestingPipelineRouteImport } from './routes/dashboard/testing-pipeline'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard/teams'
import { Route as DashboardSyncNetworkRouteImport } from './routes/dashboard/sync-network'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRepositoriesRouteImport } from './routes/dashboard/repositories'
import { Route as DashboardPatchesRouteImport } from './routes/dashboard/patches'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardImpactAnalyzerRouteImport } from './routes/dashboard/impact-analyzer'
import { Route as DashboardDeploymentsRouteImport } from './routes/dashboard/deployments'
import { Route as DashboardBackportRouteImport } from './routes/dashboard/backport'
import { Route as DashboardAutoMergeRouteImport } from './routes/dashboard/auto-merge'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAiAssistantRouteImport } from './routes/dashboard/ai-assistant'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardRepositoriesIdRouteImport } from './routes/dashboard/repositories.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUpdatesRoute = DashboardUpdatesRouteImport.update({
  id: '/dashboard/updates',
  path: '/dashboard/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTestingPipelineRoute =
  DashboardTestingPipelineRouteImport.update({
    id: '/dashboard/testing-pipeline',
    path: '/dashboard/testing-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/dashboard/teams',
  path: '/dashboard/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSyncNetworkRoute = DashboardSyncNetworkRouteImport.update({
  id: '/dashboard/sync-network',
  path: '/dashboard/sync-network',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRepositoriesRoute = DashboardRepositoriesRouteImport.update({
  id: '/dashboard/repositories',
  path: '/dashboard/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPatchesRoute = DashboardPatchesRouteImport.update({
  id: '/dashboard/patches',
  path: '/dashboard/patches',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardImpactAnalyzerRoute = DashboardImpactAnalyzerRouteImport.update({
  id: '/dashboard/impact-analyzer',
  path: '/dashboard/impact-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/dashboard/deployments',
  path: '/dashboard/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBackportRoute = DashboardBackportRouteImport.update({
  id: '/dashboard/backport',
  path: '/dashboard/backport',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAutoMergeRoute = DashboardAutoMergeRouteImport.update({
  id: '/dashboard/auto-merge',
  path: '/dashboard/auto-merge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/dashboard/audit',
  path: '/dashboard/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiAssistantRoute = DashboardAiAssistantRouteImport.update({
  id: '/dashboard/ai-assistant',
  path: '/dashboard/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRepositoriesIdRoute = DashboardRepositoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardRepositoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardLayoutRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/auto-merge': typeof DashboardAutoMergeRoute
  '/dashboard/backport': typeof DashboardBackportRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/impact-analyzer': typeof DashboardImpactAnalyzerRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patches': typeof DashboardPatchesRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync-network': typeof DashboardSyncNetworkRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/testing-pipeline': typeof DashboardTestingPipelineRoute
  '/dashboard/updates': typeof DashboardUpdatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/repositories/$id': typeof DashboardRepositoriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/auto-merge': typeof DashboardAutoMergeRoute
  '/dashboard/backport': typeof DashboardBackportRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/impact-analyzer': typeof DashboardImpactAnalyzerRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patches': typeof DashboardPatchesRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync-network': typeof DashboardSyncNetworkRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/testing-pipeline': typeof DashboardTestingPipelineRoute
  '/dashboard/updates': typeof DashboardUpdatesRoute
  '/dashboard/repositories/$id': typeof DashboardRepositoriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/_layout': typeof DashboardLayoutRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/auto-merge': typeof DashboardAutoMergeRoute
  '/dashboard/backport': typeof DashboardBackportRoute
  '/dashboard/deployments': typeof DashboardDeploymentsRoute
  '/dashboard/impact-analyzer': typeof DashboardImpactAnalyzerRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/patches': typeof DashboardPatchesRoute
  '/dashboard/repositories': typeof DashboardRepositoriesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sync-network': typeof DashboardSyncNetworkRoute
  '/dashboard/teams': typeof DashboardTeamsRoute
  '/dashboard/testing-pipeline': typeof DashboardTestingPipelineRoute
  '/dashboard/updates': typeof DashboardUpdatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/repositories/$id': typeof DashboardRepositoriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/ai-assistant'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/auto-merge'
    | '/dashboard/backport'
    | '/dashboard/deployments'
    | '/dashboard/impact-analyzer'
    | '/dashboard/notifications'
    | '/dashboard/patches'
    | '/dashboard/repositories'
    | '/dashboard/settings'
    | '/dashboard/sync-network'
    | '/dashboard/teams'
    | '/dashboard/testing-pipeline'
    | '/dashboard/updates'
    | '/dashboard/'
    | '/dashboard/repositories/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/ai-assistant'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/auto-merge'
    | '/dashboard/backport'
    | '/dashboard/deployments'
    | '/dashboard/impact-analyzer'
    | '/dashboard/notifications'
    | '/dashboard/patches'
    | '/dashboard/repositories'
    | '/dashboard/settings'
    | '/dashboard/sync-network'
    | '/dashboard/teams'
    | '/dashboard/testing-pipeline'
    | '/dashboard/updates'
    | '/dashboard/repositories/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/_layout'
    | '/dashboard/ai-assistant'
    | '/dashboard/analytics'
    | '/dashboard/audit'
    | '/dashboard/auto-merge'
    | '/dashboard/backport'
    | '/dashboard/deployments'
    | '/dashboard/impact-analyzer'
    | '/dashboard/notifications'
    | '/dashboard/patches'
    | '/dashboard/repositories'
    | '/dashboard/settings'
    | '/dashboard/sync-network'
    | '/dashboard/teams'
    | '/dashboard/testing-pipeline'
    | '/dashboard/updates'
    | '/dashboard/'
    | '/dashboard/repositories/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  DashboardAiAssistantRoute: typeof DashboardAiAssistantRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardAutoMergeRoute: typeof DashboardAutoMergeRoute
  DashboardBackportRoute: typeof DashboardBackportRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardImpactAnalyzerRoute: typeof DashboardImpactAnalyzerRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPatchesRoute: typeof DashboardPatchesRoute
  DashboardRepositoriesRoute: typeof DashboardRepositoriesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSyncNetworkRoute: typeof DashboardSyncNetworkRoute
  DashboardTeamsRoute: typeof DashboardTeamsRoute
  DashboardTestingPipelineRoute: typeof DashboardTestingPipelineRoute
  DashboardUpdatesRoute: typeof DashboardUpdatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/updates': {
      id: '/dashboard/updates'
      path: '/dashboard/updates'
      fullPath: '/dashboard/updates'
      preLoaderRoute: typeof DashboardUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/testing-pipeline': {
      id: '/dashboard/testing-pipeline'
      path: '/dashboard/testing-pipeline'
      fullPath: '/dashboard/testing-pipeline'
      preLoaderRoute: typeof DashboardTestingPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/dashboard/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sync-network': {
      id: '/dashboard/sync-network'
      path: '/dashboard/sync-network'
      fullPath: '/dashboard/sync-network'
      preLoaderRoute: typeof DashboardSyncNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/repositories': {
      id: '/dashboard/repositories'
      path: '/dashboard/repositories'
      fullPath: '/dashboard/repositories'
      preLoaderRoute: typeof DashboardRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/patches': {
      id: '/dashboard/patches'
      path: '/dashboard/patches'
      fullPath: '/dashboard/patches'
      preLoaderRoute: typeof DashboardPatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/impact-analyzer': {
      id: '/dashboard/impact-analyzer'
      path: '/dashboard/impact-analyzer'
      fullPath: '/dashboard/impact-analyzer'
      preLoaderRoute: typeof DashboardImpactAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/deployments': {
      id: '/dashboard/deployments'
      path: '/dashboard/deployments'
      fullPath: '/dashboard/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/backport': {
      id: '/dashboard/backport'
      path: '/dashboard/backport'
      fullPath: '/dashboard/backport'
      preLoaderRoute: typeof DashboardBackportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/auto-merge': {
      id: '/dashboard/auto-merge'
      path: '/dashboard/auto-merge'
      fullPath: '/dashboard/auto-merge'
      preLoaderRoute: typeof DashboardAutoMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/dashboard/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-assistant': {
      id: '/dashboard/ai-assistant'
      path: '/dashboard/ai-assistant'
      fullPath: '/dashboard/ai-assistant'
      preLoaderRoute: typeof DashboardAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/repositories/$id': {
      id: '/dashboard/repositories/$id'
      path: '/$id'
      fullPath: '/dashboard/repositories/$id'
      preLoaderRoute: typeof DashboardRepositoriesIdRouteImport
      parentRoute: typeof DashboardRepositoriesRoute
    }
  }
}

interface DashboardRepositoriesRouteChildren {
  DashboardRepositoriesIdRoute: typeof DashboardRepositoriesIdRoute
}

const DashboardRepositoriesRouteChildren: DashboardRepositoriesRouteChildren = {
  DashboardRepositoriesIdRoute: DashboardRepositoriesIdRoute,
}

const DashboardRepositoriesRouteWithChildren =
  DashboardRepositoriesRoute._addFileChildren(
    DashboardRepositoriesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  DashboardAiAssistantRoute: DashboardAiAssistantRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardAutoMergeRoute: DashboardAutoMergeRoute,
  DashboardBackportRoute: DashboardBackportRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardImpactAnalyzerRoute: DashboardImpactAnalyzerRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPatchesRoute: DashboardPatchesRoute,
  DashboardRepositoriesRoute: DashboardRepositoriesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSyncNetworkRoute: DashboardSyncNetworkRoute,
  DashboardTeamsRoute: DashboardTeamsRoute,
  DashboardTestingPipelineRoute: DashboardTestingPipelineRoute,
  DashboardUpdatesRoute: DashboardUpdatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
